### ISSUE TITLE
No suitable API installation found.

### ISSUE THREAD

**Issue by juanchehin** [ionic-team/native-run#195]
Hi, when I run 'npx cap run android' I get the following error. Any solution?

ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.

![cap](https://user-images.githubusercontent.com/40132117/126873740-5e835ebd-c0d3-45c2-b71c-eed19818bbaf.png)

**Comment by juanchehin** [comment]
Hi, in the end you were able to fix it by installing an avd module from android studio

**Comment by x-stefan** [comment]
I wish the [issue page](https://github.com/ionic-team/native-run/wiki/Android-Errors) would mention it.

[Creating a virtual device](https://developer.android.com/studio/run/managing-avds) solved the issue for me as well.

**Comment by juanchehin** [comment]
Brilliant

**Comment by jcesarmobile** [comment]
I've edited the wiki to mention the `--verbose` flag. You can use it to get better understanding of what native-run is doing and it should help with problems. Also improved the `ERR_UNSUITABLE_API_INSTALLATION` description.

Also sent https://github.com/ionic-team/native-run/pull/204, that would recommend using `--sdk-info` flag to get more information about installed/missing SDKs.
The PR also mentions that flag on the `ERR_UNSUITABLE_API_INSTALLATION` message.

**Comment by cromefire** [comment]
Sadly those options don't help at all at least in my case. Neither `--verbose` nor `--sdk-info` show any info at all and compiling and starting the project from android studio is also fine. Starting just produces:
```
✔ Copying web assets from <name> to android/app/src/main/assets/public in 4.28ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 615.66μp
✔ copy android in 13.49ms
✔ Updating Android plugins in 3.90ms
✔ update android in 16.35ms
[error] native-run failed with errors
        
        ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found. Use --sdk-info to reveal missing packages
        and other issues.
        1: undefined
        
        More details for this errors may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors
```

**Comment by jcesarmobile** [comment]
those flags are for `native-run` command, not for `cap run` command
try adding an extra `--` before the flags, that usually pass them to the following command
`npx cap run android -- --verbose --sdk-info`

**Comment by cromefire** [comment]
Yeah thanks running native-run directly worked

**Comment by mklueh** [comment]
Spent days trying to figure out what is missing. I think in my case (as I had an emulator) I needed to chown /dev/kvm to user:user, but I would never figured it out without the hint from @x-stefan !Thanks

I'm wondering, can't there be a more specific error message instead of this? It's not user friendly at all imo

**Comment by gaurav21r** [comment]
This issue is because the Android SDK versions installed don't have the relevant images installed.
On `Android Studio` go to `SDK Manager` and make sure each SDK platform checked has the relevant system image also checked (and vice versa).

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1716462/213266179-9eb62c55-c0b7-4ea3-a0eb-8ee13f30c30a.png">


If you want to know which packages are creating the problem for you, run `npm i -g native-run@latest` then `native-run android --sdk-info` in the root of your capacitor project directory.

Should solve it!

**Comment by TreehouseNorris** [comment]
Thanks @mklueh! My plugged in USB android tablet wasn't being detected by `adb devices` in terminal while Chome Inspect Devices was open in a browser tab. Closing the tab cleared the "unsuitable" error when running "npx cap run android"
