### ISSUE TITLE
Unsupported API level: 33

### ISSUE THREAD

**Issue by meiguiyisenluo** [ionic-team/native-run#239]
**Version:**

**Description:**

**Command Output:**

**SDK Info:**

**Comment by jcesarmobile** [comment]
we only support final releases, SDK 33 is still beta

**Comment by cyantree** [comment]
Do you need support for SDK 33 or do you only want to get it running?
I'm asking because I've had the same issue with creating a fresh project and installing the latest version of Android Studio.
And I only wanted to get it running. For me the hints in #219 helped.

**Comment by aguetkriegerisch** [comment]
![image](https://user-images.githubusercontent.com/39163176/177869129-82a12817-503d-43bf-8b45-2726369cda10.png)
Got the same running a simple project: I tried unninstaling 'Android API 33' and 'Android API 32 (Sv2)', still not working

**Comment by jcesarmobile** [comment]
Check the “show package details” checkbox and check all the SDK components for SDK 32. By default it doesn’t download everything that is needed.

**Comment by aguetkriegerisch** [comment]
> Check the “show package details” checkbox and check all the SDK components for SDK 32. By default it doesn’t download everything that is needed.

thanks but default selected otions seems to be enought, coz other options refers to specs that my pc doesn't have

![image](https://user-images.githubusercontent.com/39163176/177872871-3d9d76c2-dbd5-4187-bf98-273ea571aeaf.png)

you think I need to check all these options anyway? IMy processor is an Intel i7 6600

**Comment by cyantree** [comment]
Please see #219 and especially
https://github.com/ionic-team/native-run/issues/219#issuecomment-1016503975
and
https://github.com/ionic-team/native-run/issues/219#issuecomment-1170085609

This shows which System Images to download because you need to download an appropriate Android System Image to get the simulator running.

**Comment by jcesarmobile** [comment]
You don’t really need all of them, but at least one of Google APIs ARM 64, Google APIs Intel or Google Play Intel (I recommend the last one since with google play you can update the system WebView if needed and install apps).
Doesn’t need to match your computer processor since those are emulators and will emulate the architecture if needed. But intel emulators work best on intel computers, while ARM are closer to real devices.
