### ISSUE TITLE
Can native-run be used without Ionic?

### ISSUE THREAD

**Issue by koraysels** [ionic-team/native-run#32]
I have a cordova + angular 8 project that uses a lot of ionic native plugins which are awesome! RIght now I am trying to implement in app purchase which is a real pain! Especially because I have to compila and run each time... 
I want to use native-run to speed up the process and prevent me from having a mental breakdown.

I tried the following command
```native-run ios --app platforms/ios/build/device/My_App.ipa --connect --forward 8100:8100 --adress=0.0.0.0```
And it successfully launches the app
while having my angular live reloading server running on port 8100... But i see no changes in the app. (the reload server does detect chagnes and recompiles..)
Can i use native-run to achieve the much sought after liver reload functionality ?

**Comment by dwieeb** [comment]
First let me say that native-run was designed to do one thing well: deploy app binaries to Android and iOS. It does not concern itself with the concept of a "livereload server".

The biggest issue you'll find is that Cordova has JS assets that need to be included in your app apart from those compiled by the Angular CLI. When coupled with the fact that the livereload server is completely in memory, this presents a unique problem that we solved with the Ionic tooling for Angular.

There are a couple ways you can achieve livereload on devices using native-run without Ionic Framework, but both of them make use of [`@ionic/angular-toolkit`](https://github.com/ionic-team/angular-toolkit), because that's where the necessary Cordova asset magic takes place.

#### Use the Ionic CLI without Ionic Framework

This process will still use the Ionic CLI (which uses native-run), because it is convenient to simply run a single command to achieve livereload on devices.

Setup:

1. Install Ionic CLI: `npm i -g ionic`
1. In your Angular project, run `ionic init --type=angular` (this creates an `ionic.config.json` file)
1. In your `angular.json`, change the key and other references from your app name to simply `app` (project name isn't configurable in `angular` projects yet)
1. Install our schematics for running the dev server in Cordova: `npm i -D @ionic/angular-toolkit`
1. Add the following Angular architect commands to `angular.json`: https://github.com/ionic-team/starters/blob/b251e272555c793ffcf289cd676c70c40dcf7a95/angular/base/angular.json#L134-L157

Run:

1. Run `ionic cordova run ios -l`

#### Use native-run without Ionic CLI and Ionic Framework

This process is more low-level and involves invoking multiple commands and a file edit to achieve livereload on devices. It could be scripted, though.

Setup:

1. Install our schematics for running the dev server in Cordova: `npm i -D @ionic/angular-toolkit`
1. Add the following Angular architect commands to `angular.json`: https://github.com/ionic-team/starters/blob/b251e272555c793ffcf289cd676c70c40dcf7a95/angular/base/angular.json#L134-L157

Run:

1. Find your computer's IP on your WiFi network using `ifconfig` or similar commands to list network interfaces. For example, mine is `192.168.0.1`.
1. Start the livereload server with your IP: `npx ng run <PROJECT KEY>:ionic-cordova-serve --host=<YOUR IP> --platform=ios`
1. Write the IP in `<content src="<YOUR IP>" />` in `config.xml`
1. Run `cordova build ios`
1. Run `native-run ios --app platforms/ios/build/device/My_App.ipa --connect`

**Comment by koraysels** [comment]
does this work with angular 8? because I seem to have some issues with "Use the Ionic CLI without Ionic Framework"

My project has a different name than 'app' so I changed the architect files accordingly and included the `--project=<myname>` option but Istill get issues

```
$ ionic cordova run ios -l --project=oase-ang
[INFO] Hardware device(s) found for ios. Using --device.
[WARN] An external host may be required to serve for this target device/platform.
       
       If you get connection issues on your device or emulator, try connecting the device to the same Wi-Fi network and
       selecting an accessible IP address for your computer on that network.
       
       You can use --address=0.0.0.0 to run the dev server on all network interfaces, in which case an external address
       will be selected.
       
> ng run app:ionic-cordova-serve --host=localhost --port=8100 --platform=ios
[ng] Project 'app' could not be found in workspace.
[ng] Error: Project 'app' could not be found in workspace.

```

**Comment by dwieeb** [comment]
@koraysels Looks like I missed your reply. Would you mind creating an issue in ionic-cli if you think there's a bug? This now has little to do with native-run.
