### ISSUE TITLE
Unsupported API level: 34

### ISSUE THREAD

**Issue by chhaller** [ionic-team/native-run#334]
**Version:**

9.8.0

**Description:**

Creating a new Capacitor project. ``npx cap run android`` returns with
```bat
       native-run failed with error

        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

        More details for this error may be available online:
        https://github.com/ionic-team/native-run/wiki/Android-Errors
```

Docs stated to open an issue, and there seems to be no opened GitHub issue for version 34.

**Comment by dirkkelderman** [comment]
Same same!

**Comment by FoodlyEric** [comment]
I get 
        ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 33x

**Comment by ZeroHackeR** [comment]
I noticed that some of the solutions said to uninstall the latest SDK.
I don't think, this should be the way because I am using the latest SDK for other project.

So, please help us.

**Comment by Albongle** [comment]
I was able to replicate this error in windows. On my Ubuntu 20.04 operating system I had no problems

**Comment by mirkonasato** [comment]
I think this error is possibly misleading. The real problem in my case was that I didn't have _Android SDK Platform **33**_ installed (under _SDK Manager_ in _Android Studio_).  Since the generated Android project has `targetSdkVersion = 33` it makes sense that you need the exact same SDK version installed.

But I still kept _Android SDK Platform **34**_  as well.

Maybe the error should say "Please install [the right SDK version number]" rather than complaining about whatever the latest installed version happens to be.

**Comment by airtong** [comment]
Same here

**Comment by nicolae536** [comment]
Same error on macos latest version

**Comment by nicolae536** [comment]
I have the same issue on macos Sonoma

**Comment by seekinmonky** [comment]
same issue for me

**Comment by pablopereira27** [comment]
This problem happens because "Run Android" is trying to run the application on an AVD (Android Virtual Device) API 34, if you remove or edit this AVD to API 33 or run the app on a non-virtual device through the cable connected to the computer (adb devices), this problem ends.

Obviously you need:
- Have SDK 33 and the System Image (Google APIs Intel x86_64 Atom System Image), both of which can be acquired through the SDK Manager contained in Android Studio.
- Create the AVD with API 33.

**Comment by lvzhenbo** [comment]
So when will Ionic support Android 14?

**Comment by Supritha0203** [comment]
I do not have an AVD on my windows, so can anyone tell me how to change from api level 34 to 33

**Comment by keev-studio** [comment]
Same issue in Windows 10
Strange is that I was able to build sucessfully like 15 times, doing just minor html+css changes before getting this error.

**Comment by kevincam3** [comment]
Can anybody give a step by step solution for this.

**Comment by jcesarmobile** [comment]
Update to version 2.0.0

**Comment by kevincam3** [comment]
> Update to version 2.0.0

Update what to version 2.0.0?

**Comment by kevincam3** [comment]
For now I'm just building it directly in Android Studio since that works fine.

**Comment by jcesarmobile** [comment]
You are commenting on native-run repository and latest version of native-run is 2.0.0, so I mean update native-run to 2.0.0.

**Comment by lvzhenbo** [comment]
> Can anybody give a step by step solution for this.

Download these
![image](https://github.com/ionic-team/native-run/assets/32427677/76b0dd91-95c3-4ce3-b950-e873947d6674)
![image](https://github.com/ionic-team/native-run/assets/32427677/9a6be371-9cfd-4500-9cd3-35ec1caba6a9)

**Comment by SkySor44** [comment]
I have mine set up exactly like this and I still get: `ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.`

**Comment by NelsonDJCR** [comment]
> I have mine set up exactly like this and I still get: `ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.`

I got the same problem
