### ISSUE TITLE
hardware/emulation device detection seems to be broken 

### ISSUE THREAD

**Issue by Monarch73** [ionic-team/native-run#36]
My USB-Connected Galaxy Tab S2 device is reconized as emulated-device in npm paket native-run@0.2.1. There seems to be a bug in the adb.ts file.

I also think its a bad idea to determin whenever  a device is emulation or hardware by checking if its connected via IP or USB.

There is better ways. For instance
ro.sf.lcd_density usualy specifies the Displays DPI on hardware. Emulators don't provide such a value in getprop-shell command.

**Comment by dwieeb** [comment]
@Monarch73 Agreed. Our "first pass" of extracting devices from adb simply parses the output of `adb devices -l`. Then a second pass is performed which uses `adb shell getprop` to gather more details. Right now we only do hardware/emulator detection in that first pass, and I am trying to make it as accurate as possible. I just pushed a commit make it better: https://github.com/ionic-team/native-run/commit/5ec454b389fdd3be7e22bf83ae8065c12cebf885

What we really need to do sometime is to make that second pass overwrite the device details gathered from the first pass if necessary, because you're right, it's going to be more accurate. 

I have other priorities at the moment, but would love a PR if you find time/interest. You seem to have a good idea of what's going on.

**Comment by Monarch73** [comment]
V0.2.8 does not seem to have the problem anymore. I think this issue can be closed. My tablet is now beeing reconized as hardware.

But I like to let you know that the other day I was fighting with native-run because the "shell getProp" call kept failing even though the stdout seemed to be fine. It turned out it was a problem with a specific adb-version: 
**Android Debug Bridge version 1.0.41
Version 29.0.0-5611747**

**This version of adb causes the execFile-Call to throw an error even though the command executes just fine.**

Eventhough I would love to support your work and send in PRs, I am afraid I don't have the time to do so.

**Comment by dwieeb** [comment]
Yeah, the hardware/virtual detection got better in recent versions. Glad to hear it's working for you!

As for the adb issue, it wouldn't be the first time adb has had a bug. From the sound of it, nothing needs to change in `native-run`. I wouldn't want to ignore the exit code of adb and risk hiding actual errors.

No worries about the PRs. Detailed feedback like this is just as helpful. 💙
