### ISSUE TITLE
[ERROR] native-run was not found on your PATH. Please install it globally:

### ISSUE THREAD

**Issue by ozshunga** [ionic-team/native-run#72]
I tried to run  sudo npm i -g native-run
but same error.

**Comment by ozshunga** [comment]
Ionic:

   Ionic CLI                     : 5.2.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   NodeJS : v10.16.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.2.1 Build version 10E1001

**Comment by leo4444** [comment]
Hi there! I have the same problem in MAC. I installed native-run globally but I miss a path error. I already tried deleting and reinstalling several times, clearing the npm cache and also deleting and adding the platform again but without result.

A minor detail is that after installing the package globally, it does not recognize the command in native-run console. It may be due to a problem in package installation

My configuration is as follows:

Ionic:
   Ionic CLI                     : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4, ios 5.0.1

Utility:
   cordova-res : 0.6.0 
   native-run  : not installed

System:
   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.16.0 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

**Comment by dwieeb** [comment]
If you run `npm i -g native-run` and then `native-run` is not a recognized command, something is likely wrong with your NodeJS installation or npm setup. 

@leo4444 @ozshunga For you both, it looks like global packages are installed in `/usr/local/lib/node_modules`, so look for `native-run` there, and also look for the binary in `/usr/local/bin`. If they're both there, check to see if `/usr/local/bin` is in your PATH. 

It will also work if you install it in your project if you're using the Ionic CLI.

**Comment by leo4444** [comment]
@dwieeb Thanks for responding and sorry for the delay, I was not in front of the PC these days ... I searched the directories mentioned but it is not native-run. It's strange because the rest of the packages are installed (ios-deploy, ios-sim, ionic, cordova, cordova-res, etc.)
Do you have an idea what may be happening?

**Comment by dwieeb** [comment]
@leo4444 I can't really say without being in front of your computer. Like I said, something is likely wrong with your NodeJS installation or npm setup. It isn't a bug in `native-run`, but a configuration issue with NodeJS or npm on your machine.

Please feel free to take advantage of the helpful [Ionic community](https://ionicframework.com/support), but let's reserve Github for bugs and feature requests. Thanks!

**Comment by JuanNorsync** [comment]
Same problem here (macOS)
