### ISSUE TITLE
What is node-ioslib?

### ISSUE THREAD

**Issue by joshstrange** [ionic-team/native-run#82]
What is this library: `node-ioslib`? There is [no github linked on npmjs.com](https://www.npmjs.com/package/node-ioslib) and the [npm author/publisher](https://www.npmjs.com/~tlancina) appears to be an [ionic employee](https://github.com/tlancina) yet [the repo is not public on their account](https://github.com/tlancina?tab=repositories). Even more confusing there is also an [ioslib on npm](https://www.npmjs.com/package/ioslib) created by [appcelerator](https://github.com/appcelerator/ioslib) but looking at the two code bases they don't seem related (in the sense of originating from the same codebase).

It appears to have been [added here](https://github.com/ionic-team/native-run/commit/1009f8dea008c1b91755e8ff5371321dcc16ba78), I only noticed it when I was trying debug an issue originating from that library.

**Comment by tlancina** [comment]
Hey it's a very valid question!

`node-ioslib` is essentially a NodeJS port of a lot of the functionality of [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice).  

One of the primary motivations for us to build `native-run` was because of the high support load from Cordova and [ios-deploy](https://github.com/ios-control/ios-deploy) related issues, often times from the native compilation step required.

Another big part of it is that `ios-deploy` only works on macOS. The more we looked in to it, the more it seemed possible to deploy to iOS devices from Windows or Linux machines (as long as you have access to a valid Developer Disk Image). We just needed to be able to "talk" to the devices, which is where `libimobiledevice` comes in.

Since we open sourced native-run, @dwieeb has been asking me why we haven't open sourced `node-ioslib` as well.  The reality is, there were plans to use it in some of our commercial offerings (Ionic Studio), so you can think of it as sort of being in "Open Core" limbo, where we didn't want to open source everything, but still wanted the functionality for our users to be available and free in `native-run`.
